apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlinks-front
  labels:
    app: shortlinks-fron
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortlinks-front
  template:
    metadata:
      labels:
        app: shortlinks-front
    spec:
      containers:
        - name: shortlinks-front
          image: gfalk85/shortlinks-fe
          ports:
            - containerPort: 80
