version: "3"
services:
  server:
    build: ./server/
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    ports:
      - "5000:5000"
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
